const START_GAME = 'START_GAME';
const JOIN_GAME = 'JOIN_GAME';
const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const UPDATE_USERS = 'UPDATE_USERS';
const JOINED_ROOM = 'JOINED_ROOM';
const UPDATE_ROOMS = 'UPDATE_ROOMS';
const ADD_ROOM = 'ADD_ROOM';
const USER_LEFT = 'USER_LEFT';
const GET_USER_INFO = 'GET_USER_INFO';
const SEND_PICTURE = 'SEND_PICTURE';
const PICK_WORDS = 'PICK_WORDS';
const CHANGE_CATEGORIES = 'CHANGE_CATEGORIES';
const CHANGE_CATEGORIES_CLIENT = 'CHANGE_CATEGORIES_CLIENT';
const UPDATE_ROOMS_CLIENT = 'UPDAE_ROOMS_CLIENT';
const MOVE_ON = 'MOVE_ON';
const SEND_SCOREBOARD_INFO = 'SEND_SCOREBOARD_INFO';
const SEND_ROUND_INFO = 'SEND_ROUND_INFO';
const SEND_CLOCK_INFO = 'SEND_CLOCK_INFO';
const RECEIVE_CLOCK_INFO = 'RECEIVE_CLOCK_INFO'
const START_TIMER = 'START_TIMER'
const SEND_ARTIST_INFO = 'SEND_ARTIST_INFO'
const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
const GET_SELECTED_CATEGORIES = 'GET_SELECTED_CATEGORIES';
const BEGIN_ROUND = 'BEGIN_ROUND';
const CLOCK_PLAYPAGE = 'CLOCK_PLAYPAGE';
const GOT_CORRECT_WORD = 'GOT_CORRECT_WORD';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'; 

module.exports = {
    START_GAME,
    JOIN_GAME,
    SEND_MESSAGE,
    RECEIVE_MESSAGE,
    UPDATE_USERS,
    JOINED_ROOM,
    UPDATE_ROOMS,
    ADD_ROOM,
    USER_LEFT,
    GET_USER_INFO,
    PICK_WORDS,
    SEND_PICTURE,
    CHANGE_CATEGORIES,
    CHANGE_CATEGORIES_CLIENT,
    UPDATE_ROOMS_CLIENT,
    MOVE_ON,
    SEND_SCOREBOARD_INFO,
    SEND_ROUND_INFO,
    SEND_CLOCK_INFO,
    RECEIVE_CLOCK_INFO,
    START_TIMER,
    SEND_ARTIST_INFO,
    UPDATE_CATEGORIES,
    GET_SELECTED_CATEGORIES,
    BEGIN_ROUND,
    CLOCK_PLAYPAGE,
    GOT_CORRECT_WORD,
    UPDATE_USER_INFO
}